---
title: "40-modeling"
output: html_notebook
---

## Modeling

It is time to prepare my data for modeling.

The parameters of input are: 
 - category ID
 - trending date
 - publish time
 - views
 - likes
 - dislikes
 - comment_count
 - comments_disabled
 - ratings_disabled
 
 The new column I will be predicting is "duration". 
 
 
### Add new features to the original data set: 
```{r new data frame}
video_statistics_prepared <- video_statistics %>%
  #add feature engineering function here %>%
  #add feature engineering function here %>% 
  time_of_day_of_upload() %>%
  assert(in_set("morning", "afternoon", "evening", "night")) %>% 
  assign_binary_values_to_time_of_day_of_upload() %>% 
  assert(within_bounds(0,1)) %>% 
  number_of_days_trending() %>% 
  assert(within_bounds(1,50), duration_trending) %>% 


  select(duration_trending, everything())
```



### Re-arrange columns to have all parameters of interest in front
```{r select columns/parameters of interest}
video_statistics_prepared <- video_statistics_prepared %>%
  select (
    duration_trending,
    morning,
    afternoon,
    evening,
    night,
    category_id,
    views,
    likes,
    dislikes,
    comment_count,
    comments_disabled,
    ratings_disabled, 
    everything()
  )


#Inspect data:
head(video_statistics_prepared)
```

```{r csv file for new data frame}
write.csv(video_statistics_prepared,"video_statistics_prepared.csv")
```

